M2_experiment <- ECICourseTools::get_student_grades_exp()
usethis::use_data(M2_experiment)
P2_satisfaction <- ECICourseTools::get_customer_satisfaction_exp(seed = 80)
usethis::use_data(P2_satisfaction) #, overwrite = TRUE)
P3_gift <- ECICourseTools::het_treat(seed = 12345)
usethis::use_data(P3_gift, overwrite = TRUE)
M6_coupon <- ECICourseTools::get_rfm_data(.seed = 12345)
usethis::use_data(M6_coupon, overwrite = TRUE)
M7_soda_prices <- ECICourseTools::get_soda_prices()
usethis::use_data(M7_soda_prices, overwrite = TRUE)
M8_loyalty <- ECICourseTools::get_loyalty_incentive()
usethis::use_data(M8_loyalty, overwrite = TRUE)
final_obs <- ECICourseTools::get_hotel_stays(.seed = 4)
usethis::use_data(final_obs, overwrite = TRUE)
final_exp <- ECICourseTools::get_hotel_experiment(.seed = 6)
usethis::use_data(final_exp, overwrite = TRUE)


