M2_experiment <- ECICourseTools::get_student_grades_exp()
usethis::use_data(M2_experiment)
P2_satisfaction <- ECICourseTools::get_customer_satisfaction_exp(seed = 80)
usethis::use_data(P2_satisfaction)
M6_coupon <- ECICourseTools::get_rfm_data()
usethis::use_data(M6_coupon)
M7_soda_prices <- ECICourseTools::get_soda_prices()
usethis::use_data(M7_soda_prices)
M8_loyalty <- ECICourseTools::get_loyalty_incentive()
usethis::use_data(M8_loyalty)
final_obs <- ECICourseTools::get_hotel_stays(.seed = 1)
usethis::use_data(final_obs)
final_exp <- ECICourseTools::get_hotel_experiment(.seed = 2)
usethis::use_data(final_exp)
